export const USECASE_TOKENS = {
REGISTER_DRIVER_USECASE: Symbol.for("REGISTER_DRIVER_USECASE"),
EDIT_DRIVER_PROFILE: Symbol.for("EDIT_DRIVER_PROFILE"),
ONBOARD_DRIVER_USECASE: Symbol.for("ONBOARD_DRIVER_USECASE"),
//controller tokens
DRIVER_CONTROLLER:Symbol.for('DRIVER_CONTROLLER')
}