export const USECASE_TOKENS = {
  REGISTER_DRIVER_USECASE: Symbol.for("REGISTER_DRIVER_USECASE"),
  EDIT_DRIVER_PROFILE: Symbol.for("EDIT_DRIVER_PROFILE"),
  ONBOARD_DRIVER_USECASE: Symbol.for("ONBOARD_DRIVER_USECASE"),
  GET_USERBOOKINGS_USECASE: Symbol.for("GET_USERBOOKINGS_USECASE"),
  VERIFY_DRIVER_PAYMENT_ACCOUNT_USECASE: Symbol.for(
    "VERIFY_DRIVER_PAYMENT_ACCOUNT_USECASE"
  ),
  BOOK_DRIVER_USECASE: Symbol.for("BOOK_DRIVER_USECASE"),
  GET_ESTIMATED_FARE_USECASE: Symbol.for("GET_ESTIMATED_FARE_USECASE"),
  IGET_USER_BOOKINGS_USECASE: Symbol("IGetUserBookingsUseCase"),
ATTACH_PAYMENT_INTENT_USECASE: Symbol.for("IAttachPaymentIntentIdToBookingUseCase"),
  UPDATE_BOOKING_STATUS_USECASE: Symbol.for("UPDATE_BOOKING_STATUS_USECASE"),
  GET_ALL_BOOKINGS_USECASE:Symbol.for("GET_ALL_BOOKINGS_USECASE"),
  CANCEL_BOOKING_USECASE: "CANCEL_BOOKING_USECASE",
    GET_MESSAGES_BY_BOOKING_USECASE: Symbol.for("GET_MESSAGES_BY_BOOKING_USECASE"),
      DELETE_MESSAGE_USECASE: Symbol.for("DELETE_MESSAGE_USECASE"),
        GENERATE_SIGNED_URL_USECASE: Symbol.for("GENERATE_SIGNED_URL_USECASE"),
          WALLET_BALANCE_USECASE: Symbol.for("WALLET_BALANCE_USECASE"),
          WALLET_PAYMENT_USECASE: Symbol.for("WALLET_PAYMENT_USECASE"),
          GET_DRIVER_REVIEWS_USECASE: Symbol.for("GET_DRIVER_REVIEWS_USECASE"),
          GET_BOOKING_STATUS_SUMMARY_USECASE: Symbol.for("GET_BOOKING_STATUS_SUMMARY_USECASE"),
          GET_DRIVER_EARNINGS_SUMMARY_USECASE: Symbol.for("GET_DRIVER_EARNINGS_SUMMARY_USECASE"),

          

  //controller tokens
  DRIVER_CONTROLLER: Symbol.for("DRIVER_CONTROLLER"),
};
